# Generated by Django 6.0.2 on 2026-02-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tracker.company'),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
